/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UnitService } from "../unit.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UnitCreateInput } from "./UnitCreateInput";
import { UnitWhereInput } from "./UnitWhereInput";
import { UnitWhereUniqueInput } from "./UnitWhereUniqueInput";
import { UnitFindManyArgs } from "./UnitFindManyArgs";
import { UnitUpdateInput } from "./UnitUpdateInput";
import { Unit } from "./Unit";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UnitControllerBase {
  constructor(
    protected readonly service: UnitService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Unit",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Unit })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: UnitCreateInput): Promise<Unit> {
    return await this.service.create({
      data: {
        ...data,

        childProfile: data.childProfile
          ? {
              connect: data.childProfile,
            }
          : undefined,
      },
      select: {
        additionalUnitInfomation: true,

        childProfile: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        numberOfBedrooms: true,
        numberOfVacantRooms: true,
        postCode: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Unit",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Unit] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(UnitFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Unit[]> {
    const args = plainToClass(UnitFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        additionalUnitInfomation: true,

        childProfile: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        numberOfBedrooms: true,
        numberOfVacantRooms: true,
        postCode: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Unit",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Unit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: UnitWhereUniqueInput
  ): Promise<Unit | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        additionalUnitInfomation: true,

        childProfile: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        name: true,
        numberOfBedrooms: true,
        numberOfVacantRooms: true,
        postCode: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Unit",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Unit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: UnitWhereUniqueInput,
    @common.Body() data: UnitUpdateInput
  ): Promise<Unit | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          childProfile: data.childProfile
            ? {
                connect: data.childProfile,
              }
            : undefined,
        },
        select: {
          additionalUnitInfomation: true,

          childProfile: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,
          numberOfBedrooms: true,
          numberOfVacantRooms: true,
          postCode: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Unit",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Unit })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: UnitWhereUniqueInput
  ): Promise<Unit | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          additionalUnitInfomation: true,

          childProfile: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          name: true,
          numberOfBedrooms: true,
          numberOfVacantRooms: true,
          postCode: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
