/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsDate,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumChildProfileFloatingSupport } from "./EnumChildProfileFloatingSupport";
import { EnumChildProfileGender } from "./EnumChildProfileGender";
import { LocalAuthorityCreateNestedManyWithoutChildProfilesInput } from "./LocalAuthorityCreateNestedManyWithoutChildProfilesInput";
import { EnumChildProfileSemiIndependentLiving } from "./EnumChildProfileSemiIndependentLiving";
import { UnitCreateNestedManyWithoutChildProfilesInput } from "./UnitCreateNestedManyWithoutChildProfilesInput";
@InputType()
class ChildProfileCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  allergies?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  clientName?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateOfBirth?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumChildProfileFloatingSupport,
  })
  @IsEnum(EnumChildProfileFloatingSupport)
  @IsOptional()
  @Field(() => EnumChildProfileFloatingSupport, {
    nullable: true,
  })
  floatingSupport?: "Yes" | "No" | null;

  @ApiProperty({
    required: false,
    enum: EnumChildProfileGender,
  })
  @IsEnum(EnumChildProfileGender)
  @IsOptional()
  @Field(() => EnumChildProfileGender, {
    nullable: true,
  })
  gender?: "Male" | "Female" | null;

  @ApiProperty({
    required: false,
    type: () => LocalAuthorityCreateNestedManyWithoutChildProfilesInput,
  })
  @ValidateNested()
  @Type(() => LocalAuthorityCreateNestedManyWithoutChildProfilesInput)
  @IsOptional()
  @Field(() => LocalAuthorityCreateNestedManyWithoutChildProfilesInput, {
    nullable: true,
  })
  localAuthorities?: LocalAuthorityCreateNestedManyWithoutChildProfilesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nameOfKeyWorker?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumChildProfileSemiIndependentLiving,
  })
  @IsEnum(EnumChildProfileSemiIndependentLiving)
  @IsOptional()
  @Field(() => EnumChildProfileSemiIndependentLiving, {
    nullable: true,
  })
  semiIndependentLiving?: "Yes" | "No" | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  startDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => UnitCreateNestedManyWithoutChildProfilesInput,
  })
  @ValidateNested()
  @Type(() => UnitCreateNestedManyWithoutChildProfilesInput)
  @IsOptional()
  @Field(() => UnitCreateNestedManyWithoutChildProfilesInput, {
    nullable: true,
  })
  units?: UnitCreateNestedManyWithoutChildProfilesInput;
}
export { ChildProfileCreateInput };
